# Generated by Django 5.0.1 on 2024-01-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_wine_price_wine_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
